/*
**  german.h
**
**  Help topic index definitions
**  >>-- This file is generated by hlpbld --<<
*/

#ifndef LIBHELP_H
#define LIBHELP_H

#include "hlpmgrif.h"

#define HELP_INDEX_BASE          0    /* Index of Help Topics */
#define HELP_HELP                1    /* Using context-sensitive help */
#define HELP_KEYBOARD            2    /* Keyboard Functions */
#define HELP_KBD_COMMON          3    /* Key functions common to all windows */
#define HELP_KBD_EDIT            4    /* Keys used to edit input lines */
#define HELP_COMMANDS            5    /* Commands */
#define HELP_CMDS_REG_DIR        6    /* Directory commands */
#define HELP_CMDS_TAG_DIR        7    /* Tag Directory commands */
#define HELP_CMDS_ALT_DIR        8    /* Alt Directory commands */
#define HELP_CMDS_REG_FILE       9    /* File commands */
#define HELP_CMDS_TAG_FILE      10    /* Tag File commands */
#define HELP_CMDS_ALT_FILE      11    /* Alt file commands */
#define HELP_CMDS_REG_AV        12    /* Autoview commands (F7) */
#define HELP_CMDS_TAG_AV        13    /* Tag Autoview commands */
#define HELP_CMDS_ALT_AV        14    /* Alt autoview commands */
#define HELP_CMDS_REG_FV        15    /* View commands */
#define HELP_CMDS_MISC          16    /* Miscellaneous commands */
#define HELP_REG_DIR_ATTRS      17    /* Directory attributes command */
#define HELP_REG_DIR_COMPARE    18    /* Compare directory command */
#define HELP_REG_DIR_DELETE     19    /* Delete directory command */
#define HELP_REG_DIR_EDIT       20    /* Edit command */
#define HELP_REG_DIR_FILESPEC    21    /* Filespec command */
#define HELP_REG_DIR_GLOBAL     22    /* Global command */
#define HELP_REG_DIR_INVERT     23    /* Directory invert command */
#define HELP_REG_DIR_LINK       24    /* Directory link command */
#define HELP_REG_DIR_MKDIR      25    /* Make directory command */
#define HELP_REG_DIR_NODE       26    /* Node command */
#define HELP_REG_DIR_PRINT      27    /* Print directory command */
#define HELP_REG_DIR_QUIT       28    /* Quit command */
#define HELP_REG_DIR_RENAME     29    /* Rename directory command */
#define HELP_REG_DIR_SHOWALL    30    /* Showall command */
#define HELP_REG_DIR_TAG        31    /* Tag directory command */
#define HELP_REG_DIR_UNTAG      32    /* Untag directory command */
#define HELP_REG_DIR_AVAILABLE    33    /* Available space command */
#define HELP_REG_DIR_EXEC       34    /* Execute shell escape command (eXec) */
#define HELP_REG_DIR_TAGMENU    35    /* Enter Tag Menu (F3) */
#define HELP_REG_DIR_ALTMENU    36    /* Enter Alt Menu (F4) */
#define HELP_REG_DIR_HIDE       37    /* Hide directory command (F5) */
#define HELP_REG_DIR_SHOW       38    /* Show directory command (F6) */
#define HELP_REG_DIR_AUTOVIEW    39    /* Autoview Menu command (F7) */
#define HELP_REG_DIR_SPLIT      40    /* Split/Unsplit display command (F8) */
#define HELP_REG_DIR_MENU       41    /* Application Menu command (F9) */
#define HELP_REG_DIR_RELOG      42    /* Log or relog directory command (+) */
#define HELP_REG_DIR_LOG_RECURS    43    /* Recursive relog directory command (*) */
#define HELP_REG_DIR_UNLOG      44    /* Unlog directory command (-) */
#define HELP_TAG_DIR_GLOBAL     45    /* Tag global command */
#define HELP_TAG_DIR_INVERT     46    /* Tag invert command */
#define HELP_TAG_DIR_SHOWALL    47    /* Tag Showall command */
#define HELP_TAG_DIR_TAG        48    /* Tag tag command */
#define HELP_TAG_DIR_UNTAG      49    /* Tag untag command */
#define HELP_ALT_DIR_COMPACT    50    /* Compact command */
#define HELP_ALT_DIR_DIRDISP    51    /* Directory display command */
#define HELP_ALT_DIR_FILEDISP    52    /* File display command */
#define HELP_ALT_DIR_INVERT     53    /* Alt Invert command */
#define HELP_ALT_DIR_GRAFT      54    /* Graft command */
#define HELP_ALT_DIR_NODE       55    /* Alt Node command */
#define HELP_ALT_DIR_PRUNE      56    /* Prune command */
#define HELP_ALT_DIR_QUIT       57    /* Checkpoint and quit command */
#define HELP_ALT_DIR_RELEASE    58    /* Release node command */
#define HELP_ALT_DIR_SORT       59    /* Sort command */
#define HELP_ALT_DIR_TAG        60    /* Alt Tag command */
#define HELP_ALT_DIR_UNTAG      61    /* Alt Untag command */
#define HELP_ALT_DIR_HIDE       62    /* Alt Hide command (F5) */
#define HELP_ALT_DIR_SHOW       63    /* Alt Show command (F6) */
#define HELP_ALT_DIR_CONFIG     64    /* Configuration Tool (F10) */
#define HELP_REG_FILE_ATTRS     65    /* File attributes command */
#define HELP_REG_FILE_BACKUP    66    /* Backup file command */
#define HELP_REG_FILE_COPY      67    /* Copy file command */
#define HELP_REG_FILE_DELETE    68    /* Delete file command */
#define HELP_REG_FILE_EXTRACT    69    /* Extract file command */
#define HELP_REG_FILE_EDIT      70    /* Edit file command */
#define HELP_REG_FILE_FILESPEC    71    /* Filespec command */
#define HELP_REG_FILE_GOTO      72    /* Goto file command */
#define HELP_REG_FILE_INVERT    73    /* Invert file command */
#define HELP_REG_FILE_LINK      74    /* Link file command */
#define HELP_REG_FILE_MOVE      75    /* Move file command */
#define HELP_REG_FILE_NODE      76    /* Node command */
#define HELP_REG_FILE_OPEN      77    /* Open file command */
#define HELP_REG_FILE_PRINT     78    /* Print file command */
#define HELP_REG_FILE_QUIT      79    /* Quit command */
#define HELP_REG_FILE_RENAME    80    /* Rename file command */
#define HELP_REG_FILE_RESTORE    81    /* reStore files command */
#define HELP_REG_FILE_TAG       82    /* Tag File command */
#define HELP_REG_FILE_UNTAG     83    /* Untag file command */
#define HELP_REG_FILE_VIEW      84    /* View file command */
#define HELP_REG_FILE_EXEC      85    /* Execute System command (eXec) */
#define HELP_TAG_FILE_ATTRS     86    /* Tag file attributes command */
#define HELP_TAG_FILE_BACKUP    87    /* Tag file backup command */
#define HELP_TAG_FILE_COPY      88    /* Tag copy file command */
#define HELP_TAG_FILE_DELETE    89    /* Tag delete file command */
#define HELP_TAG_FILE_EXTRACT    90    /* Extract files command */
#define HELP_TAG_FILE_BATCH     91    /* shEllscript command */
#define HELP_TAG_FILE_INVERT    92    /* Tag invert file command */
#define HELP_TAG_FILE_LINK      93    /* Tag link file command */
#define HELP_TAG_FILE_MOVE      94    /* Tag move file command */
#define HELP_TAG_FILE_COMPARE    95    /* cOmpare tagged  files command */
#define HELP_TAG_FILE_PRINT     96    /* Tag print file command */
#define HELP_TAG_FILE_RENAME    97    /* Tag rename file command */
#define HELP_TAG_FILE_SEARCH    98    /* Tag search file command */
#define HELP_TAG_FILE_TAG       99    /* Tag file command */
#define HELP_TAG_FILE_UNTAG    100    /* Untag file command */
#define HELP_TAG_FILE_VIEW     101    /* View tagged file command */
#define HELP_TAG_FILE_EXEC     102    /* Tag Execute file command (eXec) */
#define HELP_ALT_FILE_COPY     103    /* Alt file copy command */
#define HELP_ALT_FILE_INVERT   104    /* Alt invert file command */
#define HELP_ALT_FILE_TAG      105    /* Alt tag file command */
#define HELP_ALT_FILE_UNTAG    106    /* Alt untag file command */
#define HELP_ALT_FILE_COPYTAGS   107    /* Merge tags command */
#define HELP_ALT_FILE_RESOLVE   108    /* Resolve symbolic link command */
#define HELP_REG_AV_SEARCH     109    /* Search for text command */
#define HELP_REG_AV_ASCII      110    /* Ascii text display command */
#define HELP_REG_AV_DUMP       111    /* Dump text display command */
#define HELP_REG_AV_HEX        112    /* Hex text display command */
#define HELP_REG_AV_KEEP       113    /* Keep current display format command */
#define HELP_REG_AV_MASK       114    /* Mask text command */
#define HELP_REG_AV_WRAP       115    /* Wrap text display command */
#define HELP_REG_AV_SRCH_NEXT   116    /* Search for next occurrence of text command */
#define HELP_REG_AV_SRCH_PREV   117    /* Search for previous occurrence of text command */
#define HELP_REG_AV_SRCH_FWD   118    /* Search forward for text command */
#define HELP_REG_AV_SRCH_BCK   119    /* Search backward for text command */
#define HELP_REG_AV_TABWIDTH   120    /* Tab width command */
#define HELP_REG_FV_NEXTFILE   121    /* Next file command (F6) */
#define HELP_REG_FV_PREVFILE   122    /* Previous file command (F5) */
#define HELP_ATTR_PERMS        123    /* Permissions */
#define HELP_ATTR_OWNER        124    /* Owner */
#define HELP_ATTR_GROUP        125    /* Group */
#define HELP_ATTR_DATE         126    /* Date */
#define HELP_TAG_INODE         127    /* Tag files by inode */
#define HELP_TAG_LINKS         128    /* Tag files by link count */
#define HELP_TAG_SIZE          129    /* Tag files by file size */
#define HELP_TAG_PERMS         130    /* Tag files by permissions */
#define HELP_TAG_OWNER         131    /* Tag files by owner */
#define HELP_TAG_GROUP         132    /* Tag files by group */
#define HELP_TAG_DATE          133    /* Tag files by date */
#define HELP_TAG_NODE          134    /* Tag files by sub-node (subdirectory) */
#define HELP_TAG_TYPE          135    /* Tag files by file type */
#define HELP_NODE_RELOG        136    /* Relog a node */
#define HELP_NODE_NEW          137    /* Log a new node */
#define HELP_NODE_ARCHIVE      138    /* Archive a backup file */
#define HELP_PRINT_PATH        139    /* Print pathnames */
#define HELP_PRINT_TREE        140    /* Print directory tree */
#define HELP_PRINT_CAT         141    /* Print catalog of tagged files */

#endif /* LIBHELP_H */
