/* ALL EDITS WILL BE LOST - This is a generated file. */

#ifndef ERRS_H
#define ERRS_H

/* Error messages */

#define ER_ACNA                 	0
#define ER_CACDCN               	1
#define ER_CAFSF                	2
#define ER_CATSF                	3
#define ER_CCCD                 	4
#define ER_CCD                  	5
#define ER_CCFTI                	6
#define ER_CCG                  	7
#define ER_CCI                  	8
#define ER_CCMP                 	9
#define ER_CCO                  	10
#define ER_CCP                  	11
#define ER_CCRN                 	12
#define ER_CCSF                 	13
#define ER_CCSL                 	14
#define ER_CCSLEF               	15
#define ER_CCWIF                	16
#define ER_CDD                  	17
#define ER_CDF                  	18
#define ER_CDIRN                	19
#define ER_CDOF                 	20
#define ER_CDRN                 	21
#define ER_CESF                 	22
#define ER_CGIY                 	23
#define ER_CGRN                 	24
#define ER_CGTY                 	25
#define ER_CGWIF                	26
#define ER_CKP                  	27
#define ER_CL                   	28
#define ER_CLD                  	29
#define ER_CLEF                 	30
#define ER_CLF                  	31
#define ER_CLFTI                	32
#define ER_CLSL                 	33
#define ER_CMD                  	34
#define ER_CMFTI                	35
#define ER_CMQA                 	36
#define ER_CMSL                 	37
#define ER_CMSPC                	38
#define ER_CO                   	39
#define ER_COBF                 	40
#define ER_COBTCH               	41
#define ER_CODF                 	42
#define ER_COF                  	43
#define ER_COHF                 	44
#define ER_COOF                 	45
#define ER_COP                  	46
#define ER_COSF                 	47
#define ER_COSPF                	48
#define ER_COTF                 	49
#define ER_CPSF                 	50
#define ER_CPWIF                	51
#define ER_CREAD                	52
#define ER_CRD                  	53
#define ER_CRF                  	54
#define ER_CRRN                 	55
#define ER_CRSL                 	56
#define ER_CRSN                 	57
#define ER_CRSYM                	58
#define ER_CRYON                	59
#define ER_CSN                  	60
#define ER_CU                   	61
#define ER_CVSF                 	62
#define ER_CWTD                 	63
#define ER_DF                   	64
#define ER_DIDN                 	65
#define ER_DNE                  	66
#define ER_DNEMNP               	67
#define ER_DNL                  	68
#define ER_DTNF                 	69
#define ER_DTOR                 	70
#define ER_DUPNM                	71
#define ER_EXISPC               	72
#define ER_FDNE                 	73
#define ER_FDNEC                	74
#define ER_FER                  	75
#define ER_FERA                 	76
#define ER_FINE                 	77
#define ER_FNE                  	78
#define ER_FNITF                	79
#define ER_FTDIFF               	80
#define ER_HNA                  	81
#define ER_IDS                  	82
#define ER_IFS                  	83
#define ER_IGN                  	84
#define ER_IM                   	85
#define ER_INAD                 	86
#define ER_INT                  	87
#define ER_IOERR                	88
#define ER_ION                  	89
#define ER_IR                   	90
#define ER_ITC                  	91
#define ER_IV                   	92
#define ER_NAMTL                	93
#define ER_NCHD                 	94
#define ER_NDE                  	95
#define ER_NESDD                	96
#define ER_NMBA                 	97
#define ER_NOAF                 	98
#define ER_NODD                 	99
#define ER_NOMENU               	100
#define ER_NOSYM                	101
#define ER_NOTBAR               	102
#define ER_NOTCPIO              	103
#define ER_NPFD                 	104
#define ER_NPTE                 	105
#define ER_NPTRF                	106
#define ER_NPTWF                	107
#define ER_NPW                  	108
#define ER_NPWPF                	109
#define ER_NTF                  	110
#define ER_NTTF                 	111
#define ER_NWPF                 	112
#define ER_PCLN                 	113
#define ER_PFD                  	114
#define ER_PWLN                 	115
#define ER_RCDP                 	116
#define ER_ROM                  	117
#define ER_RPBP                 	118
#define ER_RSFP                 	119
#define ER_RTFP                 	120
#define ER_SCHD                 	121
#define ER_TARMOD               	122
#define ER_TDNL                 	123
#define ER_TDNT                 	124
#define ER_TENA                 	125
#define ER_TF                   	126
#define ER_UEOF                 	127
#define ER_WVOL                 	128
#define ER_NOPACK               	129

#define NUM_ERRS	130

#endif /* ERRS_H */
